services:
  - type: web
    name: askify
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: prod
    healthCheckPath: /
    autoDeploy: true
