name: Production Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: askify_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        env:
          POSTGRESQL_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/askify_test
        run: |
          pytest --cov=app tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Fetch Prod Configurations
        env:
          APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          POSTGRESQL_DATABASE_URL: ${{ secrets.POSTGRESQL_DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
          GITHUB_CLIENT_ID: ${{ secrets.MY_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.MY_GITHUB_CLIENT_SECRET }}
          GITHUB_CALLBACK_URL: ${{ secrets.MY_GITHUB_CALLBACK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
        run: |
          echo "[APP]" > config.ini
          echo "SECRET_KEY = $APP_SECRET_KEY" >> config.ini
          echo "JWT_SECRET_KEY = $JWT_SECRET_KEY" >> config.ini
          echo "" >> config.ini
          echo "[POSTGRESQL]" >> config.ini
          echo "DATABASE_URL = $POSTGRESQL_DATABASE_URL" >> config.ini
          echo "" >> config.ini
          echo "[GOOGLE]" >> config.ini
          echo "CLIENT_ID = $GOOGLE_CLIENT_ID" >> config.ini
          echo "CLIENT_SECRET = $GOOGLE_CLIENT_SECRET" >> config.ini
          echo "CALLBACK_URL = $GOOGLE_CALLBACK_URL" >> config.ini
          echo "AUTHORIZE_URL = https://accounts.google.com/o/oauth2/v2/auth" >> config.ini
          echo "TOKEN_URL = https://oauth2.googleapis.com/token" >> config.ini
          echo "USER_URL = https://www.googleapis.com/oauth2/v3/userinfo" >> config.ini
          echo "SCOPES_PROFILE = https://www.googleapis.com/auth/userinfo.profile" >> config.ini
          echo "SCOPES_EMAIL = https://www.googleapis.com/auth/userinfo.email" >> config.ini
          echo "" >> config.ini
          echo "[GITHUB]" >> config.ini
          echo "CLIENT_ID = $GITHUB_CLIENT_ID" >> config.ini
          echo "CLIENT_SECRET = $GITHUB_CLIENT_SECRET" >> config.ini
          echo "CALLBACK_URL = $GITHUB_CALLBACK_URL" >> config.ini
          echo "AUTHORIZE_URL = https://github.com/login/oauth/authorize" >> config.ini
          echo "TOKEN_URL = https://github.com/login/oauth/access_token" >> config.ini
          echo "USER_URL = https://api.github.com/user" >> config.ini
          echo "" >> config.ini
          echo "[IMGBB]" >> config.ini
          echo "API_KEY = $IMGBB_API_KEY" >> config.ini

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
